layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
      - nettyHugeFileSending
      - hac
      - personal-website
      - pirosa.github.io
      - resurrect-java
      - maven-mongodb-plugin

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: attila-zsolt-piros
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Apache Spark
    web_url: https://spark.apache.org/
    image_url: https://raw.githubusercontent.com/apache/spark/master/docs/img/spark-logo-hd.png 

  - name: Scala
    web_url: https://www.scala-lang.org/
    image_url: https://raw.githubusercontent.com/scala/scala/2.13.x/src/manual/scala/tools/docutil/resources/images/scala_logo.png

  - name: Java
    web_url: https://www.java.com/en/
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/300px-Java_programming_language_logo.svg.png
